### ISSUE TITLE
Color transform is not supported?

### ISSUE THREAD

**Issue by CrazyFlasher** [rainyt/OpenFLSpine#10]
I have spine animation with color transform.
In run-time I don't see color transforms :(
[bonus.zip](https://github.com/rainyt/OpenFLSpine/files/3635873/bonus.zip)

**Comment by rainyt** [comment]
![image](https://user-images.githubusercontent.com/9693090/65365347-3caadf80-dc4b-11e9-8608-2a6e2c4220c2.png)
Is this the effect you want?

**Comment by CrazyFlasher** [comment]
Not. It differs.
You can check the source: http://188.166.108/bonus.zip

**Comment by rainyt** [comment]
![image](https://user-images.githubusercontent.com/9693090/65370296-c8dbf780-dc89-11e9-85ce-4023560ff5ad.png)
![image](https://user-images.githubusercontent.com/9693090/65370313-ff197700-dc89-11e9-8a19-7ad418fe6044.png)
![hb30](https://user-images.githubusercontent.com/9693090/65370319-0a6ca280-dc8a-11e9-8ba2-93ba9346b0c1.gif)

Sorry, I may not be able to access your IP due to regional problems, but there are new effects. Is this the case? It would be great if you could provide a GIF image to show the effect.

**Comment by CrazyFlasher** [comment]
Sorry, wrong link above:
http://188.166.108.195/bonus.zip

![image](http://188.166.108.195/spinegif.gif)

**Comment by rainyt** [comment]
Add colorTransform and blend support:https://github.com/rainyt/OpenFLSpine/commit/c0ebe4587ea516950211be5b0df2a6a25cd5972a

![image](https://user-images.githubusercontent.com/9693090/65396896-e91ccb00-dddd-11e9-9a26-d1adfc5fb0a0.png)

This will only take effect when isNative=true. Or use a Tilemap to render an object.

**Comment by rainyt** [comment]
You can update openfl-spine to version 1.4.9.
